const mockEvents = {
    "city": {
        "id": 1007700,
        "city": "München",
        "lat": 48.14,
        "lon": 11.58,
        "state": "",
        "country": "de",
        "zip": "meetup3",
        "member_count": 1257
    },
    "events": [
        {
            "created": 1595496883000,
            "duration": 50400000,
            "id": "xlnqvrybckbjc",
            "name": "55qm für Dein Meetup",
            "date_in_series_pattern": false,
            "status": "upcoming",
            "time": 1595743200000,
            "local_date": "2020-07-26",
            "local_time": "08:00",
            "updated": 1595496911000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 1,
            "venue": {
                "id": 25923646,
                "name": "Fraunbergstudio",
                "lat": 48.10029602050781,
                "lon": 11.545408248901367,
                "repinned": false,
                "address_1": "Fraunbergstrasse 3",
                "city": "München",
                "country": "de",
                "localized_country_name": "Deutschland"
            },
            "is_online_event": false,
            "group": {
                "created": 1546957368000,
                "name": "FraunbergStudio Vermietung",
                "id": 30873151,
                "join_mode": "open",
                "lat": 48.13999938964844,
                "lon": 11.579999923706055,
                "urlname": "Fraunbergtudio",
                "who": "Selbstständige",
                "localized_location": "München, Deutschland",
                "state": "",
                "country": "de",
                "region": "de_DE",
                "timezone": "Europe/Berlin"
            },
            "link": "https://www.meetup.com/de-DE/Fraunbergtudio/events/xlnqvrybckbjc/",
            "description": "<p>Du suchst noch nach der geeigneten Location für Dein Meetup? Diesen Sonntag oder auch zu einem anderen Zeitpunkt? Dann melde Dich gerne beim FraunbergStudio.de in München</p> ",
            "how_to_find_us": "U3 Thalkirchen/Tierpark",
            "visibility": "public",
            "member_pay_fee": false
        },
        {
            "created": 1580465740000,
            "duration": 7200000,
            "id": "zkdpvrybclbfb",
            "name": "Muenchner Brainstormers Club ONLINE",
            "date_in_series_pattern": false,
            "status": "upcoming",
            "time": 1596474900000,
            "local_date": "2020-08-03",
            "local_time": "19:15",
            "updated": 1595312029000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 6,
            "venue": {
                "id": 26903444,
                "name": "Online",
                "lat": 48.13512420654297,
                "lon": 11.58198070526123,
                "repinned": true,
                "address_1": "Online Adresse noch nicht verfügbar",
                "city": "München",
                "country": "de",
                "localized_country_name": "Deutschland"
            },
            "is_online_event": false,
            "group": {
                "created": 1444592791000,
                "name": "Toastmasters Clubs in and around Munich",
                "id": 19017360,
                "join_mode": "open",
                "lat": 48.13999938964844,
                "lon": 11.579999923706055,
                "urlname": "Toastmasters-Clubs-in-and-around-Munich",
                "who": "Toastmasters",
                "localized_location": "München, Deutschland",
                "state": "",
                "country": "de",
                "region": "de_DE",
                "timezone": "Europe/Berlin"
            },
            "link": "https://www.meetup.com/de-DE/Toastmasters-Clubs-in-and-around-Munich/events/zkdpvrybclbfb/",
            "description": "...",
            "how_to_find_us": "Bitte link per e-mail anfragen an: VP-PR@munich-brainstormers.de",
            "visibility": "public",
            "member_pay_fee": false
        },
        {
            "created": 1594411842000,
            "duration": 3600000,
            "id": "271846803",
            "name": "15x4 Chit-Chat Sessions 4: Dreams",
            "date_in_series_pattern": false,
            "status": "upcoming",
            "time": 1597338000000,
            "local_date": "2020-08-13",
            "local_time": "19:00",
            "updated": 1594411842000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 12,
            "venue": {
                "id": 26906060,
                "name": "Online-Event",
                "repinned": false,
                "country": "",
                "localized_country_name": ""
            },
            "is_online_event": true,
            "group": {
                "created": 1495653219000,
                "name": "15x4 Munich — Share Your Knowledge!",
                "id": 23987389,
                "join_mode": "open",
                "lat": 48.13999938964844,
                "lon": 11.579999923706055,
                "urlname": "15x4munich",
                "who": "Members",
                "localized_location": "München, Deutschland",
                "state": "",
                "country": "de",
                "region": "de_DE",
                "timezone": "Europe/Berlin"
            },
            "link": "https://www.meetup.com/de-DE/15x4munich/events/271846803/",
            "description": "",
            "how_to_find_us": "https://zoom.us/j/91452031312",
            "visibility": "public",
            "member_pay_fee": false
        },
        {
            "created": 1592158899000,
            "duration": 7200000,
            "id": "271294595",
            "name": "Ulysses (Chps. 9 - 14) - James Joyce",
            "rsvp_limit": 11,
            "date_in_series_pattern": false,
            "status": "upcoming",
            "time": 1596560400000,
            "local_date": "2020-08-04",
            "local_time": "19:00",
            "updated": 1595276180000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 11,
            "is_online_event": false,
            "group": {
                "created": 1520326534000,
                "name": "The Classic-Novels-You-Should-Have-Read-Already Bookclub",
                "id": 27741411,
                "join_mode": "approval",
                "lat": 48.13999938964844,
                "lon": 11.579999923706055,
                "urlname": "Classic-Literature-for-the-Dramatically-Stunted",
                "who": "Members",
                "localized_location": "München, Deutschland",
                "state": "",
                "country": "de",
                "region": "de_DE",
                "timezone": "Europe/Berlin"
            },
            "link": "https://www.meetup.com/de-DE/Classic-Literature-for-the-Dramatically-Stunted/events/271294595/",
            "description": "",
            "visibility": "public",
            "member_pay_fee": false
        },
        {
            "created": 1581597488000,
            "duration": 10800000,
            "id": "268680682",
            "name": "Sauerteigbrot backen am 01.08. um 15:30 Uhr",
            "date_in_series_pattern": false,
            "status": "upcoming",
            "time": 1596288600000,
            "local_date": "2020-08-01",
            "local_time": "15:30",
            "updated": 1581597488000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 1,
            "venue": {
                "id": 26662106,
                "name": "Atlanta Haus",
                "lat": 48.119056701660156,
                "lon": 11.550241470336914,
                "repinned": true,
                "address_1": "Gotzinger Str. 48",
                "city": "München",
                "country": "de",
                "localized_country_name": "Deutschland"
            },
            "is_online_event": false,
            "group": {
                "created": 1569843981000,
                "name": "Veranstaltungen rund ums Backen in München",
                "id": 32829879,
                "join_mode": "open",
                "lat": 48.13999938964844,
                "lon": 11.579999923706055,
                "urlname": "Veranstaltungen-rund-ums-Backen-in-Munchen",
                "who": "Mitglieder",
                "localized_location": "München, Deutschland",
                "state": "",
                "country": "de",
                "region": "de_DE",
                "timezone": "Europe/Berlin"
            },
            "link": "https://www.meetup.com/de-DE/Veranstaltungen-rund-ums-Backen-in-Munchen/events/268680682/",
            "description": "",
            "visibility": "public",
            "member_pay_fee": false
        },
        {
            "created": 1595602085000,
            "duration": 7200000,
            "id": "272125107",
            "name": "Motivation",
            "rsvp_limit": 10,
            "date_in_series_pattern": false,
            "status": "upcoming",
            "time": 1595995200000,
            "local_date": "2020-07-29",
            "local_time": "06:00",
            "updated": 1595602085000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 2,
            "venue": {
                "id": 26389897,
                "name": "Westpark München",
                "lat": 48.122718811035156,
                "lon": 11.509337425231934,
                "repinned": true,
                "city": "Munich",
                "country": "de",
                "localized_country_name": "Deutschland"
            },
            "is_online_event": false,
            "group": {
                "created": 1594709748000,
                "name": "Early Discussions in München",
                "id": 33963100,
                "join_mode": "open",
                "lat": 48.13999938964844,
                "lon": 11.579999923706055,
                "urlname": "early-discussions",
                "who": "Members",
                "localized_location": "München, Deutschland",
                "state": "",
                "country": "de",
                "region": "de_DE",
                "timezone": "Europe/Berlin"
            },
            "link": "https://www.meetup.com/de-DE/early-discussions/events/272125107/",
            "description": "<p>Hi all,</p> <p>let us walk in the park, starting at the fountain of Rosengarten in Westpark, near the restaurant Wirtshaus am Rosengarten.</p> <p>We will be discussing how motivation works for each of us. How long it lasts, what influences it, and what inspires us. Let's share our observation and experience in a friendly atmosphere under the rising sun.</p> <p>Make sure to write me a PM that you are joining. In case of rain the event might be postponed to another day.</p> <p>We start at 06:00 sharp, so be punctual. See you!</p> ",
            "visibility": "public",
            "member_pay_fee": false
        },
        {
            "created": 1594997628000,
            "duration": 7200000,
            "id": "271985114",
            "name": "München lernt Open Space",
            "date_in_series_pattern": false,
            "status": "upcoming",
            "time": 1599580800000,
            "local_date": "2020-09-08",
            "local_time": "18:00",
            "updated": 1594998364000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 10,
            "venue": {
                "id": 26906060,
                "name": "Online-Event",
                "repinned": false,
                "country": "",
                "localized_country_name": ""
            },
            "is_online_event": true,
            "group": {
                "created": 1594996319000,
                "name": "München lernt",
                "id": 33976442,
                "join_mode": "open",
                "lat": 48.13999938964844,
                "lon": 11.579999923706055,
                "urlname": "Munchen-lernt",
                "who": "Mitglieder",
                "localized_location": "München, Deutschland",
                "state": "",
                "country": "de",
                "region": "de_DE",
                "timezone": "Europe/Berlin"
            },
            "link": "https://www.meetup.com/de-DE/Munchen-lernt/events/271985114/",
            "description": "<p>Unser erster Open Space rund um München lernt - wir sind gespannt auf Euch und Eure Themen. Mehr Infos folgen</p> ",
            "visibility": "public",
            "member_pay_fee": false
        },
        {
            "created": 1581597243000,
            "duration": 10800000,
            "id": "268680653",
            "name": "Sauerteigbrot backen am 31.07. um 14:30 Uhr",
            "date_in_series_pattern": false,
            "status": "upcoming",
            "time": 1596198600000,
            "local_date": "2020-07-31",
            "local_time": "14:30",
            "updated": 1581597243000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 0,
            "venue": {
                "id": 26662106,
                "name": "Atlanta Haus",
                "lat": 48.119056701660156,
                "lon": 11.550241470336914,
                "repinned": true,
                "address_1": "Gotzinger Str. 48",
                "city": "München",
                "country": "de",
                "localized_country_name": "Deutschland"
            },
            "is_online_event": false,
            "group": {
                "created": 1569843981000,
                "name": "Veranstaltungen rund ums Backen in München",
                "id": 32829879,
                "join_mode": "open",
                "lat": 48.13999938964844,
                "lon": 11.579999923706055,
                "urlname": "Veranstaltungen-rund-ums-Backen-in-Munchen",
                "who": "Mitglieder",
                "localized_location": "München, Deutschland",
                "state": "",
                "country": "de",
                "region": "de_DE",
                "timezone": "Europe/Berlin"
            },
            "link": "https://www.meetup.com/de-DE/Veranstaltungen-rund-ums-Backen-in-Munchen/events/268680653/",
            "description": "",
            "visibility": "public",
            "member_pay_fee": false
        },
        {
            "created": 1594027464000,
            "duration": 5400000,
            "id": "271747100",
            "name": "SciComms without Borders: PROWIBO about bringing science to students 🎓",
            "date_in_series_pattern": false,
            "status": "upcoming",
            "time": 1596042000000,
            "local_date": "2020-07-29",
            "local_time": "19:00",
            "updated": 1595600256000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 14,
            "venue": {
                "id": 26906060,
                "name": "Online-Event",
                "repinned": false,
                "country": "",
                "localized_country_name": ""
            },
            "is_online_event": true,
            "group": {
                "created": 1593255974000,
                "name": "SciComms without Borders",
                "id": 33893791,
                "join_mode": "open",
                "lat": 48.13999938964844,
                "lon": 11.579999923706055,
                "urlname": "SciComms-without-Borders",
                "who": "Science enthusiasts",
                "localized_location": "München, Deutschland",
                "state": "",
                "country": "de",
                "region": "de_DE",
                "timezone": "Europe/Berlin"
            },
            "link": "https://www.meetup.com/de-DE/SciComms-without-Borders/events/271747100/",
            "description": "",
            "how_to_find_us": "https://zoom.us/j/93073715951?pwd=cFh2MEVlNjI1WjdveXpoUXpNSFNBdz09",
            "visibility": "public",
            "member_pay_fee": false
        },
        {
            "created": 1594409348000,
            "duration": 3600000,
            "id": "271845882",
            "name": "15x4 Chit-Chat Sessions 3: Diagnosing Infections",
            "date_in_series_pattern": false,
            "status": "upcoming",
            "time": 1596128400000,
            "local_date": "2020-07-30",
            "local_time": "19:00",
            "updated": 1594915870000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 14,
            "venue": {
                "id": 26906060,
                "name": "Online-Event",
                "repinned": false,
                "country": "",
                "localized_country_name": ""
            },
            "is_online_event": true,
            "group": {
                "created": 1495653219000,
                "name": "15x4 Munich — Share Your Knowledge!",
                "id": 23987389,
                "join_mode": "open",
                "lat": 48.13999938964844,
                "lon": 11.579999923706055,
                "urlname": "15x4munich",
                "who": "Members",
                "localized_location": "München, Deutschland",
                "state": "",
                "country": "de",
                "region": "de_DE",
                "timezone": "Europe/Berlin"
            },
            "link": "https://www.meetup.com/de-DE/15x4munich/events/271845882/",
            "description": "",
            "how_to_find_us": "https://zoom.us/j/99509614463",
            "visibility": "public",
            "member_pay_fee": false
        },
        {
            "created": 1595224822000,
            "duration": 14400000,
            "id": "272035655",
            "name": "play board games",
            "date_in_series_pattern": false,
            "status": "upcoming",
            "time": 1595779200000,
            "local_date": "2020-07-26",
            "local_time": "18:00",
            "rsvp_open_offset": "PT104H",
            "updated": 1595224839000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 46,
            "venue": {
                "id": 26947718,
                "name": "Biergarten & Restaurant am Chinesischen Turm",
                "lat": 48.151973724365234,
                "lon": 11.592218399047852,
                "repinned": false,
                "address_1": "Englischer Garten 3 ",
                "city": "München",
                "country": "de",
                "localized_country_name": "Deutschland"
            },
            "is_online_event": false,
            "group": {
                "created": 1493414929000,
                "name": "Munich Social Gaming",
                "id": 23474017,
                "join_mode": "open",
                "lat": 48.13999938964844,
                "lon": 11.579999923706055,
                "urlname": "Munich-Social-Gaming",
                "who": "Members",
                "localized_location": "München, Deutschland",
                "state": "",
                "country": "de",
                "region": "de_DE",
                "timezone": "Europe/Berlin"
            },
            "link": "https://www.meetup.com/de-DE/Munich-Social-Gaming/events/272035655/",
            "description": "<p>Hi all,</p> <p>let's play our favorite games (Uno!, Coup, Dodelido, Saboteur) in a biergarten. Unlimited participants number! We rely on your help in bringing games if you have some. Looking forward to play with you!</p> <p>Cheers<br/>Evgeniy</p> ",
            "visibility": "public",
            "member_pay_fee": false
        },
        {
            "created": 1581027679000,
            "duration": 10800000,
            "id": "dxzsnrybclbjb",
            "name": "PhD Meetup",
            "rsvp_limit": 10,
            "date_in_series_pattern": false,
            "status": "upcoming",
            "time": 1596735000000,
            "local_date": "2020-08-06",
            "local_time": "19:30",
            "rsvp_close_offset": "PT31H30M",
            "updated": 1581027679000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 10,
            "venue": {
                "id": 26849772,
                "name": "Hamburgerei Schwabing",
                "lat": 48.161231994628906,
                "lon": 11.588794708251953,
                "repinned": false,
                "address_1": "Feilitzschstraße 12",
                "city": "München",
                "country": "de",
                "localized_country_name": "Deutschland"
            },
            "is_online_event": false,
            "group": {
                "created": 1461526892000,
                "name": "PhD Meetup Munich",
                "id": 19878163,
                "join_mode": "open",
                "lat": 48.13999938964844,
                "lon": 11.579999923706055,
                "urlname": "PhD-Meetup-Munich",
                "who": "Scientists",
                "localized_location": "München, Deutschland",
                "state": "",
                "country": "de",
                "region": "de_DE",
                "timezone": "Europe/Berlin"
            },
            "link": "https://www.meetup.com/de-DE/PhD-Meetup-Munich/events/dxzsnrybclbjb/",
            "description": "<p>Hello folks,</p> <p>let's meet again to discuss genetics, art, politics, computer-chips, or whatever will come up.</p> <p>We'll change venue for every meeting. So if you know places you want to go to, we appreciate any suggestions!</p> <p>If you can't make it (even on short notice), please change your RSVP so we can book the tables accordingly!</p> <p>See you soon :)</p> ",
            "how_to_find_us": "Table is reserved on the name or one of the organizers.",
            "visibility": "public",
            "member_pay_fee": false
        },
        {
            "created": 1587368987000,
            "duration": 7200000,
            "id": "bslqrrybclbwb",
            "name": "Muenchner Brainstormers Club ONLINE MEETING",
            "date_in_series_pattern": false,
            "status": "upcoming",
            "time": 1597684500000,
            "local_date": "2020-08-17",
            "local_time": "19:15",
            "updated": 1587368987000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 4,
            "venue": {
                "id": 26903444,
                "name": "Online",
                "lat": 48.13512420654297,
                "lon": 11.58198070526123,
                "repinned": true,
                "address_1": "Online Adresse noch nicht verfügbar",
                "city": "München",
                "country": "de",
                "localized_country_name": "Deutschland"
            },
            "is_online_event": false,
            "group": {
                "created": 1444592791000,
                "name": "Toastmasters Clubs in and around Munich",
                "id": 19017360,
                "join_mode": "open",
                "lat": 48.13999938964844,
                "lon": 11.579999923706055,
                "urlname": "Toastmasters-Clubs-in-and-around-Munich",
                "who": "Toastmasters",
                "localized_location": "München, Deutschland",
                "state": "",
                "country": "de",
                "region": "de_DE",
                "timezone": "Europe/Berlin"
            },
            "link": "https://www.meetup.com/de-DE/Toastmasters-Clubs-in-and-around-Munich/events/bslqrrybclbwb/",
            "description": "",
            "how_to_find_us": "Link per E-Mail an vp-pr@munich-brainstormers.de anfordern. Camera ist erforderlich. ",
            "visibility": "public",
            "member_pay_fee": false
        },
        {
            "created": 1595151757000,
            "duration": 7200000,
            "id": "272018851",
            "name": "Assembling trust",
            "rsvp_limit": 8,
            "date_in_series_pattern": false,
            "status": "upcoming",
            "time": 1596726000000,
            "local_date": "2020-08-06",
            "local_time": "17:00",
            "updated": 1595458681000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 5,
            "venue": {
                "id": 26953736,
                "name": "Goetheplatz",
                "lat": 48.1301383972168,
                "lon": 11.556174278259277,
                "repinned": true,
                "address_1": "Goethepl.",
                "city": "München",
                "country": "de",
                "localized_country_name": "Deutschland"
            },
            "is_online_event": false,
            "group": {
                "created": 1580495568000,
                "name": "Deep Conversation",
                "id": 33278390,
                "join_mode": "open",
                "lat": 48.13999938964844,
                "lon": 11.579999923706055,
                "urlname": "deep-conversation-munich",
                "who": "Members",
                "localized_location": "München, Deutschland",
                "state": "",
                "country": "de",
                "region": "de_DE",
                "timezone": "Europe/Berlin"
            },
            "link": "https://www.meetup.com/de-DE/deep-conversation-munich/events/272018851/",
            "description": "<p>Hi all,</p> <p>let us talk in a friendly atmosphere about trust and things that influence keeping it.</p> <p>Please come prepared, it is a discussion where we share our thoughts and experiences, and learn from each other.</p> <p>Meeting point: Hans im Glück Goethepl. 2, 80337 München, at Götheplatz. We can get some drinks, and might go to Theresienwiese afterwards, if the weather is good.</p> ",
            "visibility": "public",
            "member_pay_fee": false
        },
        {
            "created": 1582567535000,
            "duration": 7200000,
            "id": "268956562",
            "name": "Mehr Frauen in den Aufsichtsräten?",
            "date_in_series_pattern": false,
            "status": "upcoming",
            "time": 1601915400000,
            "local_date": "2020-10-05",
            "local_time": "18:30",
            "updated": 1582567535000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 2,
            "venue": {
                "id": 26874339,
                "name": "FOM Hochschule Hochschulzentrum München",
                "lat": 48.14244842529297,
                "lon": 11.556012153625488,
                "repinned": false,
                "address_1": "Arnulfstraße 30",
                "city": "München",
                "country": "de",
                "localized_country_name": "Deutschland"
            },
            "is_online_event": false,
            "group": {
                "created": 1582456038000,
                "name": "München Wissensaustausch Meetup Gruppe",
                "id": 33415222,
                "join_mode": "open",
                "lat": 48.13999938964844,
                "lon": 11.579999923706055,
                "urlname": "meetup-group-HBpwEMbO",
                "who": "Mitglieder",
                "localized_location": "München, Deutschland",
                "state": "",
                "country": "de",
                "region": "de_DE",
                "timezone": "Europe/Berlin"
            },
            "link": "https://www.meetup.com/de-DE/meetup-group-HBpwEMbO/events/268956562/",
            "description": "<p>Elke Benning Rohnke, bringt eine über 30-jährige Erfahrung aus Tätigkeiten in und für internationale Konzerne mit. Ihre Kompetenzen baute sie in namhaften Unternehmen wie Procter & Gamble, Kraft Jacobs Suchard in Deutschland und Kanada auf. Bereits nach zwölf Jahren wurde sie aufgrund ihrer Erfolge in den Vorstand der Wella AG berufen. Heute berät sie namhafte Unternehmen in den Themenbereichen profitables Wachstum und Customer Centricity. Elke Benning-Rohnke hält Aufsichtsrats- und Beiratsmandate und ist auch Aufsichtsratsvorsitzende einer mittelständischen AG .</p> ",
            "visibility": "public",
            "member_pay_fee": false
        },
        {
            "created": 1595155937000,
            "duration": 7200000,
            "id": "272019427",
            "name": "Philosophieren und Freunde finden - philosophize and make friends",
            "rsvp_limit": 20,
            "date_in_series_pattern": false,
            "status": "upcoming",
            "time": 1595779200000,
            "local_date": "2020-07-26",
            "local_time": "18:00",
            "updated": 1595155937000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 9,
            "venue": {
                "id": 26906060,
                "name": "Online-Event",
                "repinned": false,
                "country": "",
                "localized_country_name": ""
            },
            "is_online_event": true,
            "group": {
                "created": 1546246724000,
                "name": "Philosophieren und Freunde finden",
                "id": 30806436,
                "join_mode": "approval",
                "lat": 48.13999938964844,
                "lon": 11.579999923706055,
                "urlname": "Philosophieren-Diskutieren-Kennenlernen",
                "who": "Leute",
                "localized_location": "München, Deutschland",
                "state": "",
                "country": "de",
                "region": "de_DE",
                "timezone": "Europe/Berlin"
            },
            "link": "https://www.meetup.com/de-DE/Philosophieren-Diskutieren-Kennenlernen/events/272019427/",
            "description": "",
            "visibility": "public",
            "member_pay_fee": false
        },
        {
            "created": 1592159336000,
            "duration": 7200000,
            "id": "271294652",
            "name": "Ulysses (Chps. 15 - 18 + Overall) - James Joyce",
            "date_in_series_pattern": false,
            "status": "upcoming",
            "time": 1602003600000,
            "local_date": "2020-10-06",
            "local_time": "19:00",
            "updated": 1592161928000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 8,
            "is_online_event": false,
            "group": {
                "created": 1520326534000,
                "name": "The Classic-Novels-You-Should-Have-Read-Already Bookclub",
                "id": 27741411,
                "join_mode": "approval",
                "lat": 48.13999938964844,
                "lon": 11.579999923706055,
                "urlname": "Classic-Literature-for-the-Dramatically-Stunted",
                "who": "Members",
                "localized_location": "München, Deutschland",
                "state": "",
                "country": "de",
                "region": "de_DE",
                "timezone": "Europe/Berlin"
            },
            "link": "https://www.meetup.com/de-DE/Classic-Literature-for-the-Dramatically-Stunted/events/271294652/",
            "description": "",
            "visibility": "public",
            "member_pay_fee": false
        },
        {
            "created": 1579002790000,
            "duration": 7200000,
            "id": "267903276",
            "name": "LoL-Spezial - Lachstern, tiefe Entspannung und das Gefühlsquadrat",
            "date_in_series_pattern": false,
            "status": "upcoming",
            "time": 1597770000000,
            "local_date": "2020-08-18",
            "local_time": "19:00",
            "updated": 1579002790000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 3,
            "venue": {
                "id": 26174054,
                "name": "Alten- und Service-Zentrum Laim",
                "lat": 48.134281158447266,
                "lon": 11.514219284057617,
                "repinned": true,
                "address_1": "Kiem-Pauli-Weg 22",
                "city": "München",
                "country": "de",
                "localized_country_name": "Deutschland"
            },
            "is_online_event": false,
            "group": {
                "created": 1549822652000,
                "name": "LoL-Training München",
                "id": 31133430,
                "join_mode": "open",
                "lat": 48.13999938964844,
                "lon": 11.579999923706055,
                "urlname": "LOL-Training-Munchen",
                "who": "Mitglieder",
                "localized_location": "München, Deutschland",
                "state": "",
                "country": "de",
                "region": "de_DE",
                "timezone": "Europe/Berlin"
            },
            "link": "https://www.meetup.com/de-DE/LOL-Training-Munchen/events/267903276/",
            "description": "",
            "how_to_find_us": "U-Bahnhaltestelle Friedenheimer Strasse, und 5 Min. Fußweg.",
            "visibility": "public",
            "member_pay_fee": false
        },
        {
            "created": 1582621200000,
            "duration": 7200000,
            "id": "268973460",
            "name": "Brezeln selber backen am 21.08. um 15:30",
            "date_in_series_pattern": false,
            "status": "upcoming",
            "time": 1598016600000,
            "local_date": "2020-08-21",
            "local_time": "15:30",
            "updated": 1582621200000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 0,
            "venue": {
                "id": 26856570,
                "name": "Gotzinger Str. 48",
                "lat": 48.11911392211914,
                "lon": 11.550498008728027,
                "repinned": false,
                "address_1": "Gotzinger Str. 48",
                "city": "München",
                "country": "de",
                "localized_country_name": "Deutschland"
            },
            "is_online_event": false,
            "group": {
                "created": 1569843981000,
                "name": "Veranstaltungen rund ums Backen in München",
                "id": 32829879,
                "join_mode": "open",
                "lat": 48.13999938964844,
                "lon": 11.579999923706055,
                "urlname": "Veranstaltungen-rund-ums-Backen-in-Munchen",
                "who": "Mitglieder",
                "localized_location": "München, Deutschland",
                "state": "",
                "country": "de",
                "region": "de_DE",
                "timezone": "Europe/Berlin"
            },
            "link": "https://www.meetup.com/de-DE/Veranstaltungen-rund-ums-Backen-in-Munchen/events/268973460/",
            "description": "",
            "visibility": "public",
            "member_pay_fee": false
        },
        {
            "created": 1588705075000,
            "duration": 5400000,
            "id": "bnjbsrybclbgb",
            "name": "Chinese/ German Club in Munich",
            "rsvp_limit": 13,
            "date_in_series_pattern": false,
            "status": "upcoming",
            "time": 1596560400000,
            "local_date": "2020-08-04",
            "local_time": "19:00",
            "updated": 1588705075000,
            "utc_offset": 7200000,
            "waitlist_count": 0,
            "yes_rsvp_count": 4,
            "venue": {
                "id": 26903444,
                "name": "Online",
                "lat": 48.13512420654297,
                "lon": 11.58198070526123,
                "repinned": true,
                "address_1": "Online Adresse noch nicht verfügbar",
                "city": "München",
                "country": "de",
                "localized_country_name": "Deutschland"
            },
            "is_online_event": false,
            "group": {
                "created": 1444592791000,
                "name": "Toastmasters Clubs in and around Munich",
                "id": 19017360,
                "join_mode": "open",
                "lat": 48.13999938964844,
                "lon": 11.579999923706055,
                "urlname": "Toastmasters-Clubs-in-and-around-Munich",
                "who": "Toastmasters",
                "localized_location": "München, Deutschland",
                "state": "",
                "country": "de",
                "region": "de_DE",
                "timezone": "Europe/Berlin"
            },
            "link": "https://www.meetup.com/de-DE/Toastmasters-Clubs-in-and-around-Munich/events/bnjbsrybclbgb/",
            "description": "",
            "how_to_find_us": "PM Hongnan to get an invite",
            "visibility": "public",
            "member_pay_fee": false
        }
    ]
}

export { mockEvents }